<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="/app/css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<?php
$page = "utenti";

?>

<body>
    <?php include "components/header.html" ?>

    <main>
        <div class="side-menu">
            <?php
            include "components/navbar.php"
            ?>
            <hr>
            <div id="filter">
                <form action="#">
                    <label for="nomeutente">Nome utente</label>
                    <input type="text" placeholder="Nome utente" name="nomeutente">


                    <label for="nome">Nome</label>
                    <input type="text" placeholder="Nome" name="nome">


                    <label for="cognome">Cognome</label>
                    <input type="text" placeholder="Cognome" name="cognome">


                    <label for="email">Email</label>
                    <input type="text" placeholder="Email" name="email">
                    <input type="submit">
                </form>
            </div>

        </div>
        <div class="content">

            <table>
                <thead>
                    <th>Colonna 1</th>
                    <th>Colonna 2</th>
                    <th>Colonna 3</th>
                    <th>Colonna 4</th>
                </thead>
                <tbody>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                    <tr>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                        <td>dato</td>
                    </tr>
                </tbody>

            </table>
        </div>
    </main>
    <?php
    include "components/footer.html"
    ?>
</body>

</html>